- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f  #  take this from ur ec2
    sg_id: sg-0386fad148560778b  # take this from ur ec2
    zone_id: Z04936233JDYCWRJS57S7 # take this from ur ec2 
    domain_name: "rakesh12.fun"
    instances:
    - mongodb

  tasks: 
  - name: create ec2 instance
    amazon.aws.ec2_instance:    # take this from chrome (examples) / refear notes
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  # - name: print public_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  # - name: print private_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"