- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f  # took this from my shell-roboshop project / u can also take this from ur ec2
    sg_id: sg-009fa2b813b96b24d # took this from my shell-roboshop project 
    zone_id: Z07005331VKQNOA14SRCD # took this from my shell-roboshop project 
    domain_name: "rakesh12.fun"
    instances:
    - mongodb

  tasks: 
  - name: create ec2 instance
    amazon.aws.ec2_instance:    # take this from chrome (examples) / refear notes
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
